name: Monitor AWS Resources
  hosts: localhost
  tasks:
    - name: Fetch EC2 facts
      ec2_instance_facts:
        aws_access_key: " " 
        aws_secret_key: " " 
        region: "us-east-1"
      register: ec2_facts

    - name: Display EC2 facts
      debug:
        var: ec2_facts
